In [ ]:
#House price prediction
import numpy as np

# Input features (house characteristics like rooms,area in sq.ft,location index)
X = np.array([
    [3, 1500, 0.7],
    [2, 800, 0.5],
    [4, 2500, 0.8],
    [5, 3500, 0.9],
    [3, 2000, 0.6]
])


Y = np.array([[400000], [150000], [600000], [800000], [500000]])

# Initialize weights and bias
W = np.random.rand(3, 1)
b = np.random.rand(1)


lr = 0.0000001
epochs = 1000


def linear(x):
    return x

# Loss function
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)


In [ ]:
# Training model(loop)
for epoch in range(epochs):
    z = np.dot(X, W) + b
    A = linear(z)

    loss = mse_loss(Y, A)
    d_loss = 2 * (A - Y) / len(Y)

    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    W -= lr * dW
    b -= lr * db


    if epoch % 100== 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")


output = linear(np.dot(X, W) + b)
print("\nFinal Predictions (House Prices):")
print(output.round(2))

Epoch 0, Loss: 285637701253.1356
Epoch 100, Loss: 1030124840.0964
Epoch 200, Loss: 1030124504.7055
Epoch 300, Loss: 1030124169.3202
Epoch 400, Loss: 1030123833.9406
Epoch 500, Loss: 1030123498.5666
Epoch 600, Loss: 1030123163.1983
Epoch 700, Loss: 1030122827.8355
Epoch 800, Loss: 1030122492.4785
Epoch 900, Loss: 1030122157.1270

Final Predictions (House Prices):
[[355652.96]
 [189682.44]
 [592753.17]
 [829853.37]
 [474202.46]]


In [ ]:
#span email detection
import numpy as np

# Columns might represent: [keyword frequency, sender score, email length]
X = np.array([
    [0.9, 0.2, 100],
    [0.1, 0.9, 200],
    [0.8, 0.3, 80],
    [0.2, 0.8, 180],
    [0.85, 0.1, 90],
    [0.3, 0.7, 170],
])

# Corresponding labels: 1 = Spam, 0 = Not Spam
Y = np.array([[1], [0], [1], [0], [1], [0]])

# Normalize the third column (email length) for better learning
X[:, 2] = X[:, 2] / np.max(X[:, 2])

W = np.random.rand(X.shape[1], 1)  # 3 features
b = np.random.rand(1)


lr = 0.1
epochs = 1000




In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Binary cross-entropy loss
def cross_entropy_loss(y_true, y_pred):
    eps = 1e-15  # avoid log(0)
    y_pred = np.clip(y_pred, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true)* np.log(1 - y_pred))


In [ ]:
# Training loop
for epoch in range(epochs):
    # Forward pass
    z = np.dot(X, W) + b
    A = sigmoid(z)


    loss = cross_entropy_loss(Y, A)
    d_loss = A - Y


    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    # Update weights and bias
    W -= lr * dW
    b -= lr * db

    # Print progress
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# Final predictions
output = sigmoid(np.dot(X, W) + b)
print("\nFinal Predictions:")
print(output.round())


Epoch 0, Loss: 0.8384
Epoch 100, Loss: 0.0813
Epoch 200, Loss: 0.0428
Epoch 300, Loss: 0.0291
Epoch 400, Loss: 0.0221
Epoch 500, Loss: 0.0179
Epoch 600, Loss: 0.0150
Epoch 700, Loss: 0.0129
Epoch 800, Loss: 0.0114
Epoch 900, Loss: 0.0102

Final Predictions:
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [ ]:
#Student's Placement
import numpy as np

# Example dataset: [10th %, 12th %, CGPA, IQ score]
X = np.array([
    [85, 78, 8.5, 120],
    [60, 65, 6.0, 90],
    [75, 80, 7.2, 110],
    [55, 58, 5.8, 85],
    [90, 88, 9.0, 130],
    [50, 55, 5.5, 80],
])

Y = np.array([[1], [0], [1], [0], [1], [0]])

# Normalize features
X = X / np.max(X, axis=0)  # column-wise normalization

W = np.random.rand(X.shape[1], 1)
b = np.random.rand(1)

lr = 0.1
epochs = 1000

# Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Binary Cross-Entropy Loss
def cross_entropy_loss(y_true, y_pred):
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))




In [ ]:
# Training Loop
for epoch in range(epochs):
    z = np.dot(X, W) + b
    A = sigmoid(z)

    loss = cross_entropy_loss(Y, A)
    d_loss = A - Y

    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    # Update parameters
    W -= lr * dW
    b -= lr * db


    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

#Final Predictions
output = sigmoid(np.dot(X, W) + b)
print("\nFinal Predictions (Rounded):")
print(output.round())

Epoch 0, Loss: 1.0480
Epoch 100, Loss: 0.4345
Epoch 200, Loss: 0.3221
Epoch 300, Loss: 0.2567
Epoch 400, Loss: 0.2144
Epoch 500, Loss: 0.1848
Epoch 600, Loss: 0.1630
Epoch 700, Loss: 0.1462
Epoch 800, Loss: 0.1328
Epoch 900, Loss: 0.1219

Final Predictions (Rounded):
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [ ]:
#forecast temperature
import numpy as np

# Sample input: [Temp(t-3), Temp(t-2), Temp(t-1), Humidity(t-1), WindSpeed(t-1)]
X = np.array([
    [28, 29, 30, 60, 12],
    [29, 30, 31, 65, 14],
    [30, 31, 32, 58, 11],
    [31, 32, 33, 55, 10],
    [32, 33, 34, 57, 13],
])

Y = np.array([[31], [32], [33], [34], [35]])

X = X / np.max(X, axis=0)

W = np.random.rand(X.shape[1], 1)
b = np.random.rand(1)

lr = 0.1
epochs = 1000

def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)



In [ ]:
 #Training loop
for epoch in range(epochs):
    z = np.dot(X, W) + b
    loss = mse_loss(Y, z)

    d_loss = 2 * (z - Y) / Y.shape[0]
    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    W -= lr * dW
    b -= lr * db

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# Final predictions
predicted_temp = np.dot(X, W) + b
print("\nForecasted Temperatures:")
print(predicted_temp)


Epoch 0, Loss: 0.0062
Epoch 100, Loss: 0.0057
Epoch 200, Loss: 0.0053
Epoch 300, Loss: 0.0049
Epoch 400, Loss: 0.0045
Epoch 500, Loss: 0.0042
Epoch 600, Loss: 0.0039
Epoch 700, Loss: 0.0036
Epoch 800, Loss: 0.0033
Epoch 900, Loss: 0.0031

Forecasted Temperatures:
[[31.09310149]
 [31.9654467 ]
 [33.01207364]
 [34.00274468]
 [34.93309188]]
